# Generated by Django 4.2.14 on 2024-07-28 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('expense_id', models.AutoField(primary_key=True, serialize=False)),
                ('expense_amount', models.FloatField()),
                ('category', models.CharField(choices=[('equal', 'Equal'), ('percentage', 'Percentage'), ('exact', 'Exact')], max_length=10)),
                ('description', models.TextField()),
                ('payer', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default='unknown', on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('participant_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField(default=0.0)),
                ('percentage', models.FloatField(default=0.0)),
                ('paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='expenses.expense')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='user.user')),
            ],
        ),
    ]
