# Generated by Django 4.2.14 on 2024-07-28 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('mobile_phone', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=128)),
                ('balance', models.FloatField(default=0.0)),
            ],
        ),
    ]
